ci:
  autofix_prs: false
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'
  skip: [poetry-lock]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-json
  - id: check-toml
    exclude: |
        (?x)^(
            cookiecutter/.*/pyproject.toml
        )$
  - id: check-yaml
    exclude: |
        (?x)^(
            cookiecutter/.*/meltano.yml
        )$
  - id: end-of-file-fixer
    exclude: |
      (?x)^(
        cookiecutter/.*|
        docs/.*|
        samples/.*\.json|
        tests/snapshots/.*/.*\.json
      )$
  - id: trailing-whitespace
    exclude: |
        (?x)^(
            .bumpversion.cfg|
            singer_sdk/helpers/_simpleeval.py|
            tests/core/test_simpleeval.py
        )$

- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    exclude: |
        (?x)^(
            cookiecutter/.*|
            singer_sdk/helpers/_simpleeval.py|
            tests/core/test_simpleeval.py
        )$

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.231'
  hooks:
    - id: ruff
      # Respect `exclude` and `extend-exclude` settings.
      args: ["--force-exclude", "--fix"]
      files: 'singer_sdk/.*'

- repo: https://github.com/pycqa/isort
  rev: 5.11.4
  hooks:
  - id: isort
    exclude: (cookiecutter/.*|singer_sdk/helpers/_simpleeval/.*)

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies:
    - darglint==1.8.1
    files: 'singer_sdk/.*'

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
    exclude: |
        (?x)^(
            singer_sdk/helpers/_simpleeval.py|
            tests/core/test_simpleeval.py
        )$

- repo: https://github.com/python-poetry/poetry
  rev: 1.3.2
  hooks:
  - id: poetry-check
  - id: poetry-lock
    args: [--no-update]
